black:
  max:
  - 89
  - 255
  - 255
  min:
  - 0
  - 0
  - 0
blue:
  max:
  - 255
  - 255
  - 108
  min:
  - 0
  - 0
  - 0
green:
  max:
  - 150
  - 120
  - 160
  min:
  - 60
  - 0
  - 100
red:
  max:
  - 255
  - 255
  - 255
  min:
  - 0
  - 140
  - 100
white:
  max:
  - 255
  - 255
  - 255
  min:
  - 193
  - 0
  - 0
gray:
  max:
  - 200
  - 180
  - 120
  min:
  - 20
  - 110
  - 110

